"""Build script: inject CSS/JS into HTML → generate embedded.py.

Usage:
    python -m aioncode.internal.dashboard.frontend.build_frontend

Reads static/{index.html, style.css, app.js, monitor.html} and produces
embedded.py with EMBEDDED_HTML and EMBEDDED_MONITOR_HTML string constants.
Zero static/ file path dependency at runtime.
"""

from __future__ import annotations

import re
from pathlib import Path

STATIC_DIR = Path(__file__).parent / "static"
OUTPUT_FILE = Path(__file__).parent / "embedded.py"


def _inject_assets(html: str, static_dir: Path) -> str:
    """Replace <link href> and <script src> with inline content."""

    # Inline CSS: <link rel="stylesheet" href="/static/style.css">
    def replace_css(match):
        href = match.group(1)
        filename = href.split("/")[-1]
        css_file = static_dir / filename
        if css_file.exists():
            css = css_file.read_text(encoding="utf-8")
            return f"<style>\n{css}\n</style>"
        return match.group(0)

    html = re.sub(
        r'<link\s+rel="stylesheet"\s+href="([^"]+)"\s*/?>',
        replace_css,
        html,
    )

    # Inline JS: <script src="/static/app.js"></script>
    def replace_js(match):
        src = match.group(1)
        filename = src.split("/")[-1]
        js_file = static_dir / filename
        if js_file.exists():
            js = js_file.read_text(encoding="utf-8")
            return f"<script>\n{js}\n</script>"
        return match.group(0)

    html = re.sub(
        r'<script\s+src="([^"]+)"\s*></script>',
        replace_js,
        html,
    )

    return html


def build() -> None:
    """Build embedded.py from static files."""
    index_html = STATIC_DIR / "index.html"
    monitor_html = STATIC_DIR / "monitor.html"

    if not index_html.exists():
        print(f"ERROR: {index_html} not found")
        return

    # Build main dashboard HTML
    main_html = index_html.read_text(encoding="utf-8")
    main_html = _inject_assets(main_html, STATIC_DIR)

    # Build monitor HTML (already self-contained with inline CSS/JS)
    monitor = ""
    if monitor_html.exists():
        monitor = monitor_html.read_text(encoding="utf-8")

    # Escape triple quotes in content
    main_html_escaped = main_html.replace('"""', '\\"\\"\\"')
    monitor_escaped = monitor.replace('"""', '\\"\\"\\"')

    output = f'''"""Embedded HTML — auto-generated by build_frontend.py.

DO NOT EDIT MANUALLY. Run: python -m aioncode.internal.dashboard.frontend.build_frontend
"""

EMBEDDED_HTML = """{main_html_escaped}"""

EMBEDDED_MONITOR_HTML = """{monitor_escaped}"""
'''

    OUTPUT_FILE.write_text(output, encoding="utf-8")
    print(f"Generated {OUTPUT_FILE}")
    print(f"  EMBEDDED_HTML: {len(main_html)} chars")
    print(f"  EMBEDDED_MONITOR_HTML: {len(monitor)} chars")


if __name__ == "__main__":
    build()
