"""Embedded HTML — auto-generated by build_frontend.py.

DO NOT EDIT MANUALLY. Run: python -m aioncode.internal.dashboard.frontend.build_frontend
"""

EMBEDDED_HTML = """<!DOCTYPE html>
<html lang="zh-CN">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>AionCode — 副驾驶</title>
<link rel="preconnect" href="https://fonts.googleapis.com">
<link href="https://fonts.googleapis.com/css2?family=Inter:wght@400;500;600;700&family=JetBrains+Mono:wght@400;500;700&display=swap" rel="stylesheet">
<style>
/* AionCode Copilot — Core layout + theme */

/* ── Dark theme (default) ── */
:root, [data-theme="dark"] {
  --bg-deep: #0c0e12;
  --bg: #111318;
  --bg-raised: #181b22;
  --bg-hover: #1e222b;
  --bg-active: #252a35;
  --border: #262b36;
  --border-subtle: #1c2028;
  --border-focus: #4c7bd9;
  --text-primary: #d8dce6;
  --text-secondary: #8891a0;
  --text-tertiary: #555d6e;
  --text-inverse: #0c0e12;
  --accent: #6b9eff;
  --accent-dim: rgba(107, 158, 255, 0.10);
  --accent-text: #8db8ff;
  --success: #4eca6a;
  --warning: #e6a730;
  --danger: #e65c50;
  --shadow-overlay: rgba(0,0,0,0.5);
  --code-bg: #0d0f14;
}

/* ── Light theme ── */
[data-theme="light"] {
  --bg-deep: #f0f0ee;
  --bg: #f7f7f5;
  --bg-raised: #ffffff;
  --bg-hover: #eaeae8;
  --bg-active: #e2e2df;
  --border: #d5d5d0;
  --border-subtle: #e5e5e1;
  --border-focus: #4c7bd9;
  --text-primary: #1a1c20;
  --text-secondary: #5a5e68;
  --text-tertiary: #8b8f98;
  --text-inverse: #ffffff;
  --accent: #3574e0;
  --accent-dim: rgba(53, 116, 224, 0.08);
  --accent-text: #2960c4;
  --success: #2d8a4e;
  --warning: #b8860b;
  --danger: #d1453b;
  --shadow-overlay: rgba(0,0,0,0.2);
  --code-bg: #f0f0ee;
}

:root {
  --font-ui: 'Inter', -apple-system, BlinkMacSystemFont, system-ui, sans-serif;
  --font-mono: 'JetBrains Mono', 'SF Mono', 'Fira Code', 'Consolas', monospace;
  --rail-w: 48px;
  --sidebar-w: 280px;
  --header-h: 40px;
  --statusbar-h: 24px;
  --ease-out: cubic-bezier(0.16, 1, 0.3, 1);
  --dur-fast: 120ms;
  --dur-normal: 200ms;
}

*, *::before, *::after { margin: 0; padding: 0; box-sizing: border-box; }

body {
  font-family: var(--font-ui);
  font-size: 12px;
  background: var(--bg-deep);
  color: var(--text-primary);
  height: 100vh;
  display: flex;
  overflow: hidden;
  -webkit-font-smoothing: antialiased;
  line-height: 1.45;
}

/* ── Rail ── */
.rail {
  width: var(--rail-w);
  background: var(--bg);
  border-right: 1px solid var(--border-subtle);
  display: flex;
  flex-direction: column;
  align-items: center;
  padding: 6px 0;
  gap: 2px;
  z-index: 100;
}
.rail-btn {
  width: 32px; height: 32px;
  border: none; background: transparent;
  color: var(--text-tertiary);
  border-radius: 6px;
  cursor: pointer;
  display: flex; align-items: center; justify-content: center;
  transition: all var(--dur-fast) var(--ease-out);
  position: relative;
}
.rail-btn:hover { background: var(--bg-hover); color: var(--text-secondary); }
.rail-btn.active { color: var(--accent); background: var(--accent-dim); }
.rail-btn .tip {
  display: none; position: absolute; left: 42px;
  background: var(--bg-raised); border: 1px solid var(--border);
  color: var(--text-primary); padding: 2px 8px; border-radius: 4px;
  white-space: nowrap; font-size: 11px; box-shadow: 0 4px 12px rgba(0,0,0,0.4);
  z-index: 200; pointer-events: none;
}
.rail-btn:hover .tip { display: block; }
.rail-sep { flex: 1; }
.rail-divider { width: 20px; height: 1px; background: var(--border-subtle); margin: 4px 0; }

/* ── Main ── */
.main { flex: 1; display: flex; flex-direction: column; min-width: 0; }

.header {
  height: var(--header-h);
  display: flex; align-items: center;
  padding: 0 12px; gap: 10px;
  background: var(--bg);
  border-bottom: 1px solid var(--border-subtle);
  flex-shrink: 0;
}
.header select {
  background: var(--bg-deep); color: var(--text-primary);
  border: 1px solid var(--border); border-radius: 4px;
  padding: 3px 8px; font-size: 11px; font-family: var(--font-ui);
  outline: none; cursor: pointer; max-width: 160px;
}
.header select:focus { border-color: var(--border-focus); }
.header .path { font-size: 11px; color: var(--text-tertiary); font-family: var(--font-mono); overflow: hidden; text-overflow: ellipsis; white-space: nowrap; }
.header .spacer { flex: 1; }
.kbd-hint { font-size: 10px; color: var(--text-tertiary); display: flex; align-items: center; gap: 3px; }
kbd { background: var(--bg-deep); border: 1px solid var(--border); border-radius: 3px; padding: 0 4px; font-family: var(--font-mono); font-size: 10px; line-height: 16px; color: var(--text-secondary); }

/* ── Content: Sidebar + Detail ── */
.content { flex: 1; display: flex; overflow: hidden; }

/* ── Sidebar ── */
.sidebar {
  width: var(--sidebar-w);
  min-width: var(--sidebar-w);
  background: var(--bg);
  border-right: 1px solid var(--border-subtle);
  overflow-y: auto;
  overflow-x: hidden;
  display: flex;
  flex-direction: column;
}
.sw-title {
  padding: 6px 12px;
  font-size: 10px;
  font-weight: 600;
  text-transform: uppercase;
  letter-spacing: 0.8px;
  color: var(--text-tertiary);
  display: flex;
  align-items: center;
  gap: 6px;
  position: sticky;
  top: 0;
  background: var(--bg);
  z-index: 1;
}
.sw-badge {
  font-size: 10px;
  background: var(--accent-dim);
  color: var(--accent-text);
  padding: 0 5px;
  border-radius: 8px;
  font-weight: 500;
  line-height: 16px;
  margin-left: auto;
}
.sw-badge.warn { background: rgba(230,167,48,0.12); color: var(--warning); }
.sw-body { padding: 0 8px 8px; }

/* ── Detail Pane ── */
.detail { flex: 1; overflow: auto; background: var(--bg-deep); }
.detail-welcome {
  display: flex; flex-direction: column;
  align-items: center; justify-content: center;
  height: 100%; color: var(--text-tertiary); gap: 8px;
}
.welcome-icon { font-size: 36px; opacity: 0.15; }
.welcome-title { font-size: 16px; font-weight: 600; color: var(--text-secondary); }
.welcome-hint { font-size: 12px; display: flex; align-items: center; gap: 4px; }

/* ── View switching ── */
.view-sidebar { display: flex; flex-direction: column; flex: 1; overflow-y: auto; }
.view-sidebar.hidden { display: none; }

/* ── Theme toggle ── */
.theme-toggle {
  border: none; background: transparent; color: var(--text-tertiary);
  cursor: pointer; padding: 2px 6px; border-radius: 3px; font-size: 13px;
  transition: all var(--dur-fast);
}
.theme-toggle:hover { background: var(--bg-hover); color: var(--text-primary); }

/* ── Light theme overrides ── */
[data-theme="light"] ::-webkit-scrollbar-thumb { background: var(--border); }
[data-theme="light"] ::-webkit-scrollbar-thumb:hover { background: var(--text-tertiary); }
[data-theme="light"] .rail { box-shadow: 1px 0 0 var(--border-subtle); }
[data-theme="light"] .sidebar { box-shadow: 1px 0 0 var(--border-subtle); }

/* ── Command Palette ── */
.palette-bg {
  display: none; position: fixed; inset: 0;
  background: var(--shadow-overlay); backdrop-filter: blur(3px);
  z-index: 1000; align-items: flex-start; justify-content: center;
  padding-top: min(18vh, 140px);
}
.palette-bg.open { display: flex; }
.palette {
  width: 480px; max-width: 92vw;
  background: var(--bg-raised); border: 1px solid var(--border);
  border-radius: 10px; box-shadow: 0 16px 48px rgba(0,0,0,0.5);
  overflow: hidden;
  animation: palIn var(--dur-normal) var(--ease-out);
}
@keyframes palIn { from { opacity: 0; transform: translateY(-6px) scale(0.98); } }
.palette input {
  width: 100%; padding: 12px 14px;
  background: transparent; border: none;
  border-bottom: 1px solid var(--border-subtle);
  color: var(--text-primary); font-size: 14px;
  font-family: var(--font-ui); outline: none;
}
.palette input::placeholder { color: var(--text-tertiary); }
.palette-list { max-height: 260px; overflow-y: auto; padding: 4px 0; }
.palette-opt {
  display: flex; align-items: center;
  padding: 7px 14px; gap: 10px; cursor: pointer;
  transition: background var(--dur-fast); font-size: 13px;
}
.palette-opt:hover, .palette-opt.sel { background: var(--accent-dim); }
.palette-opt .ico { width: 16px; text-align: center; font-size: 13px; }
.palette-opt .lbl { flex: 1; }
.palette-opt .key { font-size: 10px; color: var(--text-tertiary); font-family: var(--font-mono); }

/* ── Status Bar ── */
.statusbar {
  height: var(--statusbar-h);
  background: var(--bg);
  border-top: 1px solid var(--border-subtle);
  display: flex; align-items: center;
  padding: 0 10px; gap: 10px;
  font-size: 10px; color: var(--text-tertiary);
  flex-shrink: 0;
}
.status-dot { width: 5px; height: 5px; border-radius: 50%; background: var(--success); }
.status-dot.off { background: var(--text-tertiary); }
.status-dot.err { background: var(--danger); }
.statusbar .sep { color: var(--border); }

/* ── Scrollbar ── */
::-webkit-scrollbar { width: 5px; height: 5px; }
::-webkit-scrollbar-track { background: transparent; }
::-webkit-scrollbar-thumb { background: var(--border); border-radius: 3px; }
::-webkit-scrollbar-thumb:hover { background: var(--text-tertiary); }

:focus-visible { outline: 2px solid var(--border-focus); outline-offset: 1px; }
@media (prefers-reduced-motion: reduce) { *, *::before, *::after { animation-duration: 0.01ms !important; transition-duration: 0.01ms !important; } }

</style>
<style>
/* views.css — View-specific styles for AionCode Dashboard
   Separated from style.css to keep concerns clean.
   Covers: sidebar widgets, detail panels, data views. */

/* === Stats widget === */
.sw-stats { display: flex; flex-wrap: wrap; gap: 4px; padding: 4px 8px 8px; }
.stat { flex: 1 1 auto; min-width: 68px; background: var(--bg-deep); border-radius: 5px; padding: 6px 8px; text-align: center; border: 1px solid transparent; transition: border-color var(--dur-fast); cursor: default; }
.stat:hover { border-color: var(--border); }
.stat-val { font-size: 16px; font-weight: 700; font-family: var(--font-mono); color: var(--text-primary); line-height: 1.1; }
.stat-lbl { font-size: 9px; color: var(--text-tertiary); text-transform: uppercase; letter-spacing: 0.5px; margin-top: 1px; }

/* === File tree === */
.fnode { display: flex; align-items: center; padding: 2px 6px; gap: 5px; border-radius: 4px; cursor: pointer; font-family: var(--font-mono); font-size: 11px; color: var(--text-secondary); transition: all var(--dur-fast); }
.fnode:hover { background: var(--bg-hover); color: var(--text-primary); }
.fnode.active { background: var(--accent-dim); color: var(--accent-text); }
.fnode.dir { color: var(--text-secondary); font-weight: 500; }
.fnode .ico { width: 12px; font-size: 10px; text-align: center; flex-shrink: 0; color: var(--text-tertiary); }
.fnode.dir .ico { color: var(--accent-text); }
.fnode .sz { margin-left: auto; font-size: 9px; color: var(--text-tertiary); }
.fnode-children.closed { display: none; }

/* === Events === */
.evt { display: flex; gap: 6px; padding: 3px 4px; font-size: 11px; border-radius: 3px; cursor: pointer; transition: background var(--dur-fast); }
.evt:hover { background: var(--bg-hover); }
.evt-ts { color: var(--text-tertiary); font-family: var(--font-mono); font-size: 10px; min-width: 48px; }
.evt-msg { color: var(--text-secondary); overflow: hidden; text-overflow: ellipsis; white-space: nowrap; }
.live-dot { display: inline-block; width: 6px; height: 6px; border-radius: 50%; background: var(--success); animation: pulse 2s ease-in-out infinite; }
@keyframes pulse { 0%,100% { opacity: 1; } 50% { opacity: 0.3; } }

/* === Bugs === */
.bug { display: flex; align-items: center; gap: 6px; padding: 4px; font-size: 11px; border-radius: 3px; cursor: pointer; transition: background var(--dur-fast); }
.bug:hover { background: var(--bg-hover); }
.bug-dot { width: 6px; height: 6px; border-radius: 50%; flex-shrink: 0; }
.bug-dot.critical { background: var(--danger); }
.bug-dot.high { background: #db6d28; }
.bug-dot.medium { background: var(--warning); }
.bug-dot.low { background: var(--success); }
.bug-id { font-family: var(--font-mono); font-size: 10px; color: var(--accent-text); min-width: 48px; }
.bug-title { flex: 1; overflow: hidden; text-overflow: ellipsis; white-space: nowrap; }
.tag { font-size: 9px; padding: 0 4px; border-radius: 3px; background: var(--bg-deep); color: var(--text-tertiary); line-height: 16px; }

/* === Team === */
.member { display: flex; align-items: center; gap: 8px; padding: 4px; }
.avatar { width: 22px; height: 22px; border-radius: 5px; background: linear-gradient(135deg, var(--accent-dim), var(--accent)); display: flex; align-items: center; justify-content: center; font-weight: 700; font-size: 10px; color: var(--text-inverse); flex-shrink: 0; }
.member-name { font-weight: 500; font-size: 12px; }
.member-role { font-size: 10px; color: var(--text-tertiary); }

/* === Empty state === */
.empty { text-align: center; padding: 12px 8px; color: var(--text-tertiary); font-size: 11px; }
.empty .ico { font-size: 16px; margin-bottom: 4px; opacity: 0.4; }

/* === Detail: file viewer === */
.detail-file { height: 100%; display: flex; flex-direction: column; }
.detail-file-header { display: flex; align-items: center; padding: 8px 16px; gap: 8px; background: var(--bg); border-bottom: 1px solid var(--border-subtle); font-size: 12px; flex-shrink: 0; }
.detail-file-header .fname { font-family: var(--font-mono); color: var(--accent-text); }
.detail-file-header .fpath { color: var(--text-tertiary); font-size: 11px; }
.detail-file-header .spacer { flex: 1; }
.detail-file-header .close-btn { border: none; background: transparent; color: var(--text-tertiary); cursor: pointer; padding: 2px 6px; border-radius: 3px; font-size: 14px; }
.detail-file-header .close-btn:hover { background: var(--bg-hover); color: var(--danger); }
.detail-file pre { flex: 1; padding: 12px 16px; font-family: var(--font-mono); font-size: 12px; line-height: 1.6; color: var(--text-secondary); overflow: auto; white-space: pre-wrap; word-break: break-all; }

/* === Detail: bug viewer === */
.detail-bug { padding: 20px; }
.detail-bug h2 { font-size: 16px; margin-bottom: 10px; }
.detail-bug .meta { display: flex; gap: 6px; margin-bottom: 16px; flex-wrap: wrap; }
.detail-bug .body { font-size: 13px; line-height: 1.7; white-space: pre-wrap; color: var(--text-secondary); }

/* === Detail: overview / monitor / team === */
.detail-overview, .detail-monitor, .detail-team { padding: 16px 20px; overflow-y: auto; height: 100%; }
.do-section { margin-bottom: 20px; }
.do-title { font-size: 12px; font-weight: 600; color: var(--text-secondary); margin-bottom: 10px; letter-spacing: 0.02em; }
.do-grid { display: grid; grid-template-columns: repeat(3, 1fr); gap: 8px; }
.do-card { background: var(--bg); border: 1px solid var(--border-subtle); border-radius: 6px; padding: 12px; text-align: center; transition: border-color var(--dur-fast); }
.do-card:hover { border-color: var(--border); }
.do-card-val { font-size: 22px; font-weight: 700; font-family: var(--font-mono); color: var(--text-primary); }
.do-card-lbl { font-size: 10px; color: var(--text-tertiary); margin-top: 2px; }
.do-entry { padding: 8px 0; border-bottom: 1px solid var(--border-subtle); }
.do-entry:last-child { border-bottom: none; }
.do-entry-head { font-size: 12px; font-weight: 500; color: var(--accent-text); }
.do-entry-body { font-size: 11px; color: var(--text-tertiary); margin-top: 3px; line-height: 1.5; }
.do-session { display: flex; gap: 12px; padding: 6px 0; border-bottom: 1px solid var(--border-subtle); font-size: 11px; }
.do-session:last-child { border-bottom: none; }
.do-session-ts { color: var(--text-tertiary); font-family: var(--font-mono); font-size: 10px; }
.do-session-info { color: var(--text-secondary); }
.do-bar-row { display: flex; align-items: center; gap: 8px; padding: 4px 0; font-size: 11px; }
.do-bar-label { min-width: 56px; color: var(--text-secondary); font-family: var(--font-mono); font-size: 11px; }
.do-bar-track { flex: 1; height: 6px; background: var(--bg); border-radius: 3px; overflow: hidden; }
.do-bar-fill { height: 100%; background: var(--accent); border-radius: 3px; transition: width 0.3s var(--ease-out); }
.do-bar-val { min-width: 28px; text-align: right; color: var(--text-tertiary); font-family: var(--font-mono); font-size: 10px; }
.do-file-item { font-size: 11px; font-family: var(--font-mono); color: var(--text-secondary); padding: 2px 0; }
.do-member-card { display: flex; align-items: center; gap: 12px; padding: 10px 0; border-bottom: 1px solid var(--border-subtle); }
.do-member-card:last-child { border-bottom: none; }
.do-kv { display: flex; justify-content: space-between; padding: 5px 0; border-bottom: 1px solid var(--border-subtle); font-size: 11px; }
.do-kv:last-child { border-bottom: none; }
.do-kv-k { color: var(--text-secondary); }
.do-kv-v { color: var(--text-tertiary); font-family: var(--font-mono); }

/* === About page === */
.about { padding: 32px 40px; overflow-y: auto; height: 100%; }
.about h1 { font-size: 20px; font-weight: 700; margin-bottom: 4px; }
.about .subtitle { color: var(--text-tertiary); font-size: 13px; margin-bottom: 24px; }
.about h2 { font-size: 14px; font-weight: 600; color: var(--accent-text); margin: 24px 0 8px; scroll-margin-top: 16px; }
.about p, .about li { font-size: 13px; line-height: 1.7; color: var(--text-secondary); }
.about ul, .about ol { padding-left: 20px; margin: 4px 0; }
.about li { margin-bottom: 4px; }
.about ol li { padding-left: 2px; }
.about .flow { display: flex; flex-wrap: wrap; gap: 6px; margin: 8px 0; align-items: center; }
.about .flow-step { background: var(--bg); border: 1px solid var(--border-subtle); border-radius: 5px; padding: 4px 10px; font-size: 11px; font-weight: 500; color: var(--text-secondary); }
.about .flow-arrow { color: var(--text-tertiary); font-size: 11px; }
.about .key-table { width: 100%; border-collapse: collapse; margin: 8px 0; }
.about .key-table th { text-align: left; font-size: 11px; color: var(--text-tertiary); padding: 4px 8px; border-bottom: 1px solid var(--border-subtle); font-weight: 500; }
.about .key-table td { font-size: 12px; padding: 6px 8px; border-bottom: 1px solid var(--border-subtle); color: var(--text-secondary); }
.about .key-table td:first-child { font-weight: 500; color: var(--text-primary); }

/* === Data view list items === */
.data-item { padding: 6px 8px; border-radius: 4px; cursor: pointer; transition: background var(--dur-fast); border-bottom: 1px solid var(--border-subtle); }
.data-item:last-child { border-bottom: none; }
.data-item:hover { background: var(--bg-hover); }
.data-item.active { background: var(--accent-dim); }
.data-item-title { font-size: 12px; font-weight: 500; color: var(--text-primary); overflow: hidden; text-overflow: ellipsis; white-space: nowrap; }
.data-item-meta { font-size: 10px; color: var(--text-tertiary); margin-top: 2px; display: flex; align-items: center; gap: 6px; }

/* === Frontmatter table === */
.fm-table { width: 100%; border-collapse: collapse; margin-bottom: 16px; background: var(--bg); border-radius: 6px; overflow: hidden; border: 1px solid var(--border-subtle); }
.fm-table td { padding: 6px 12px; font-size: 11px; border-bottom: 1px solid var(--border-subtle); }
.fm-table td:first-child { color: var(--text-tertiary); font-weight: 500; width: 120px; background: var(--bg-deep); }
.fm-table td:last-child { color: var(--text-secondary); font-family: var(--font-mono); font-size: 11px; }
.fm-table tr:last-child td { border-bottom: none; }

/* === Status badges === */
.fm-badge { display: inline-block; font-size: 10px; padding: 1px 6px; border-radius: 3px; font-weight: 500; line-height: 16px; }
.fm-badge.completed { background: rgba(78, 202, 106, 0.15); color: var(--success); }
.fm-badge.active, .fm-badge.in_progress { background: var(--accent-dim); color: var(--accent-text); }
.fm-badge.deprecated { background: rgba(230, 92, 80, 0.12); color: var(--danger); text-decoration: line-through; }
.fm-badge.pending { background: rgba(230, 167, 48, 0.12); color: var(--warning); }

/* === Markdown rendered content === */
.md-content { padding: 20px 24px; overflow-y: auto; height: 100%; line-height: 1.7; }
.md-content h1 { font-size: 18px; font-weight: 700; margin: 0 0 12px; color: var(--text-primary); }
.md-content h2 { font-size: 14px; font-weight: 600; margin: 20px 0 8px; color: var(--accent-text); }
.md-content h3 { font-size: 13px; font-weight: 600; margin: 16px 0 6px; color: var(--text-primary); }
.md-content p { font-size: 13px; color: var(--text-secondary); margin: 6px 0; }
.md-content ul, .md-content ol { padding-left: 20px; margin: 4px 0; }
.md-content li { font-size: 13px; color: var(--text-secondary); margin-bottom: 3px; }
.md-content code { font-family: var(--font-mono); font-size: 11px; background: var(--code-bg); padding: 1px 5px; border-radius: 3px; color: var(--accent-text); }
.md-content pre { background: var(--code-bg); border: 1px solid var(--border-subtle); border-radius: 6px; padding: 12px; overflow-x: auto; margin: 8px 0; font-family: var(--font-mono); font-size: 11px; line-height: 1.5; color: var(--text-secondary); }
.md-content pre code { background: none; padding: 0; }
.md-content strong { color: var(--text-primary); font-weight: 600; }
.md-content table { width: 100%; border-collapse: collapse; margin: 8px 0; }
.md-content th { text-align: left; font-size: 11px; font-weight: 500; color: var(--text-tertiary); padding: 4px 8px; border-bottom: 1px solid var(--border-subtle); }
.md-content td { font-size: 12px; padding: 5px 8px; border-bottom: 1px solid var(--border-subtle); color: var(--text-secondary); }
.md-content hr { border: none; border-top: 1px solid var(--border-subtle); margin: 16px 0; }

/* === Checklist specific === */
.check-row { display: flex; align-items: center; gap: 6px; padding: 3px 0; font-size: 12px; color: var(--text-secondary); }
.check-box { width: 14px; height: 14px; border: 1.5px solid var(--border); border-radius: 3px; flex-shrink: 0; display: flex; align-items: center; justify-content: center; font-size: 10px; }
.check-box.checked { background: var(--success); border-color: var(--success); color: #fff; }
.check-progress { height: 4px; background: var(--bg-deep); border-radius: 2px; overflow: hidden; flex: 1; max-width: 60px; }
.check-progress-fill { height: 100%; background: var(--success); border-radius: 2px; transition: width 0.3s var(--ease-out); }

/* === Changelog entry === */
.cl-entry { padding: 6px 8px; border-bottom: 1px solid var(--border-subtle); cursor: pointer; border-radius: 4px; transition: background var(--dur-fast); }
.cl-entry:hover { background: var(--bg-hover); }
.cl-entry.active { background: var(--accent-dim); }
.cl-entry-date { font-size: 10px; color: var(--text-tertiary); font-family: var(--font-mono); }
.cl-entry-title { font-size: 11px; color: var(--text-secondary); overflow: hidden; text-overflow: ellipsis; white-space: nowrap; margin-top: 1px; }

/* === Rule specific === */
.rule-group-header { font-size: 10px; font-weight: 600; text-transform: uppercase; letter-spacing: 0.5px; color: var(--text-tertiary); padding: 8px 8px 4px; margin-top: 4px; }
.rule-cite { font-size: 9px; font-family: var(--font-mono); color: var(--text-tertiary); background: var(--bg-deep); padding: 0 4px; border-radius: 3px; line-height: 14px; }

</style>
</head>
<body>

<!-- Icon Rail -->
<nav class="rail">
  <!-- Core views -->
  <button class="rail-btn active" data-view="overview" onclick="switchView('overview')" aria-label="概览">
    <svg width="16" height="16" viewBox="0 0 16 16" fill="currentColor"><rect x="1" y="1" width="6" height="6" rx="1"/><rect x="9" y="1" width="6" height="6" rx="1"/><rect x="1" y="9" width="6" height="6" rx="1"/><rect x="9" y="9" width="6" height="6" rx="1"/></svg>
    <span class="tip">概览</span>
  </button>
  <button class="rail-btn" data-view="files" onclick="switchView('files')" aria-label="文件">
    <svg width="16" height="16" viewBox="0 0 16 16" fill="currentColor"><path d="M1.5 2A1.5 1.5 0 013 .5h4.379a1.5 1.5 0 011.06.44l3.122 3.12A1.5 1.5 0 0112 5.122V13.5A1.5 1.5 0 0110.5 15h-7A1.5 1.5 0 012 13.5V3.5H1.5zM3 2v11.5a.5.5 0 00.5.5h7a.5.5 0 00.5-.5V5.621L7.879 2.5H3.5A.5.5 0 003 2z"/></svg>
    <span class="tip">文件</span>
  </button>
  <button class="rail-btn" data-view="monitor" onclick="switchView('monitor')" aria-label="监控">
    <svg width="16" height="16" viewBox="0 0 16 16" fill="currentColor"><path d="M8 1a.5.5 0 01.5.5v5.793l3.354 3.354a.5.5 0 01-.708.708l-3.5-3.5A.5.5 0 017.5 7.5v-6A.5.5 0 018 1z"/><path d="M8 0a8 8 0 100 16A8 8 0 008 0zM1 8a7 7 0 1114 0A7 7 0 011 8z"/></svg>
    <span class="tip">监控</span>
  </button>
  <!-- Data views -->
  <div class="rail-divider"></div>
  <button class="rail-btn" data-view="specs" onclick="switchView('specs')" aria-label="需求">
    <svg width="16" height="16" viewBox="0 0 16 16" fill="currentColor"><path d="M4 0a2 2 0 00-2 2v12a2 2 0 002 2h8a2 2 0 002-2V2a2 2 0 00-2-2H4zm1 3h6v1H5V3zm0 3h6v1H5V6zm0 3h4v1H5V9z"/></svg>
    <span class="tip">需求</span>
  </button>
  <button class="rail-btn" data-view="plans" onclick="switchView('plans')" aria-label="方案">
    <svg width="16" height="16" viewBox="0 0 16 16" fill="currentColor"><path d="M2 2h12v2H2V2zm0 4h8v2H2V6zm0 4h10v2H2v-2zm0 4h6v2H2v-2z"/></svg>
    <span class="tip">方案</span>
  </button>
  <button class="rail-btn" data-view="rules" onclick="switchView('rules')" aria-label="规则">
    <svg width="16" height="16" viewBox="0 0 16 16" fill="currentColor"><path d="M8 0L2 3v5c0 4.17 2.56 7.27 6 8 3.44-.73 6-3.83 6-8V3L8 0zm0 2.18l4 1.78v4.04c0 3.04-1.77 5.44-4 6.12C5.77 13.44 4 11.04 4 8V3.96l4-1.78z"/></svg>
    <span class="tip">规则</span>
  </button>
  <button class="rail-btn" data-view="checklists" onclick="switchView('checklists')" aria-label="清单">
    <svg width="16" height="16" viewBox="0 0 16 16" fill="currentColor"><path d="M3 3h2v2H3V3zm4 0h6v1H7V3zM3 7h2v2H3V7zm4 0h6v1H7V7zM3 11h2v2H3v-2zm4 0h6v1H7v-2z"/></svg>
    <span class="tip">清单</span>
  </button>
  <button class="rail-btn" data-view="bugs" onclick="switchView('bugs')" aria-label="缺陷">
    <svg width="16" height="16" viewBox="0 0 16 16" fill="currentColor"><circle cx="8" cy="8" r="3"/><path d="M2.5 8H0M16 8h-2.5M8 2.5V0M8 16v-2.5M3.17 3.17L1.4 1.4M14.6 14.6l-1.77-1.77M3.17 12.83L1.4 14.6M14.6 1.4l-1.77 1.77" stroke="currentColor" stroke-width="1.2" fill="none"/></svg>
    <span class="tip">缺陷</span>
  </button>
  <button class="rail-btn" data-view="test" onclick="switchView('test')" aria-label="测试">
    <svg width="16" height="16" viewBox="0 0 16 16" fill="currentColor"><path d="M6 1v5H2l6 9V9h4L6 1zm1 2.5L10.25 9H7v4.5L3.75 8H7V3.5z"/></svg>
    <span class="tip">测试</span>
  </button>
  <button class="rail-btn" data-view="changelog" onclick="switchView('changelog')" aria-label="日志">
    <svg width="16" height="16" viewBox="0 0 16 16" fill="currentColor"><path d="M8 1a7 7 0 100 14A7 7 0 008 1zM0 8a8 8 0 1116 0A8 8 0 010 8zm8-4.5v5l3.5 2-.5.87L7 9.13V3.5h1z"/></svg>
    <span class="tip">日志</span>
  </button>
  <!-- Bottom -->
  <div class="rail-sep"></div>
  <button class="rail-btn" data-view="team" onclick="switchView('team')" aria-label="团队">
    <svg width="16" height="16" viewBox="0 0 16 16" fill="currentColor"><path d="M6 8a3 3 0 100-6 3 3 0 000 6zm-5 6s-1 0-1-1 1-4 6-4 6 3 6 4-1 1-1 1H1zm9-1.5a.5.5 0 01.5-.5H12V10a.5.5 0 011 0v2h1.5a.5.5 0 010 1H13v2a.5.5 0 01-1 0v-2h-1.5a.5.5 0 01-.5-.5z"/></svg>
    <span class="tip">团队</span>
  </button>
  <button class="rail-btn" data-view="about" onclick="switchView('about')" aria-label="关于">
    <svg width="16" height="16" viewBox="0 0 16 16" fill="currentColor"><path d="M8 15A7 7 0 118 1a7 7 0 010 14zm0 1A8 8 0 108 0a8 8 0 000 16z"/><path d="M8.93 6.588l-2.29.287-.082.38.45.083c.294.07.352.176.288.469l-.738 3.468c-.194.897.105 1.319.808 1.319.545 0 1.178-.252 1.465-.598l.088-.416c-.2.176-.492.246-.686.246-.275 0-.375-.193-.304-.533L8.93 6.588zM9 4.5a1 1 0 11-2 0 1 1 0 012 0z"/></svg>
    <span class="tip">关于</span>
  </button>
  <button class="rail-btn" onclick="openPalette()" aria-label="命令面板">
    <svg width="16" height="16" viewBox="0 0 16 16" fill="currentColor"><path d="M11.742 10.344a6.5 6.5 0 10-1.397 1.398h-.001l3.85 3.85a1 1 0 001.415-1.414l-3.85-3.85zm-5.242.656a5 5 0 110-10 5 5 0 010 10z"/></svg>
    <span class="tip">⌘K</span>
  </button>
</nav>

<!-- Main -->
<div class="main">
  <div class="header">
    <select id="proj-sel" onchange="switchProject(this.value)"><option>加载中...</option></select>
    <span class="path" id="proj-path"></span>
    <span class="spacer"></span>
    <button class="theme-toggle" onclick="toggleTheme()" title="切换主题" id="theme-btn">☀</button>
    <span class="kbd-hint"><kbd>⌘</kbd><kbd>K</kbd> 命令面板</span>
  </div>

  <div class="content">
    <!-- Sidebar: changes per view -->
    <div class="sidebar" id="sidebar">
      <!-- Overview sidebar -->
      <div class="view-sidebar" id="vs-overview">
        <div class="sw-title">项目概览</div>
        <div class="sw-stats" id="stats"></div>
        <div class="sw-title" style="margin-top:4px">最近活动</div>
        <div class="sw-body" id="changelog"></div>
      </div>
      <!-- Files sidebar -->
      <div class="view-sidebar hidden" id="vs-files">
        <div class="sw-title">资源管理器</div>
        <div class="sw-body" id="ftree"></div>
      </div>
      <!-- Monitor sidebar -->
      <div class="view-sidebar hidden" id="vs-monitor">
        <div class="sw-title"><span class="live-dot" id="live-dot" style="display:none"></span>实时事件 <span class="sw-badge" id="b-events">—</span></div>
        <div class="sw-body" id="events"></div>
      </div>
      <!-- Bugs sidebar -->
      <div class="view-sidebar hidden" id="vs-bugs">
        <div class="sw-title">缺陷列表 <span class="sw-badge" id="b-bugs">—</span></div>
        <div class="sw-body" id="bugs"></div>
      </div>
      <!-- Team sidebar -->
      <div class="view-sidebar hidden" id="vs-team">
        <div class="sw-title">团队成员</div>
        <div class="sw-body" id="team"></div>
      </div>
      <!-- Data view sidebars -->
      <div class="view-sidebar hidden" id="vs-specs">
        <div class="sw-title">需求文档 <span class="sw-badge" id="b-specs">—</span></div>
        <div class="sw-body" id="specs-list"></div>
      </div>
      <div class="view-sidebar hidden" id="vs-plans">
        <div class="sw-title">实施方案 <span class="sw-badge" id="b-plans">—</span></div>
        <div class="sw-body" id="plans-list"></div>
      </div>
      <div class="view-sidebar hidden" id="vs-rules">
        <div class="sw-title">项目规则 <span class="sw-badge" id="b-rules">—</span></div>
        <div class="sw-body" id="rules-list"></div>
      </div>
      <div class="view-sidebar hidden" id="vs-checklists">
        <div class="sw-title">工作清单 <span class="sw-badge" id="b-checklists">—</span></div>
        <div class="sw-body" id="checklists-list"></div>
      </div>
      <div class="view-sidebar hidden" id="vs-test">
        <div class="sw-title">测试报告 <span class="sw-badge" id="b-test">—</span></div>
        <div class="sw-body" id="test-list"></div>
      </div>
      <div class="view-sidebar hidden" id="vs-changelog">
        <div class="sw-title">变更日志 <span class="sw-badge" id="b-changelog">—</span></div>
        <div class="sw-body" id="changelog-list"></div>
      </div>
      <!-- About sidebar (TOC) -->
      <div class="view-sidebar hidden" id="vs-about">
        <div class="sw-title">使用指南</div>
        <div class="sw-body" id="about-toc"></div>
      </div>
    </div>

    <!-- Detail: changes per selection -->
    <div class="detail" id="detail"></div>
  </div>

  <div class="statusbar">
    <span class="status-dot" id="s-dot"></span>
    <span id="s-proj">—</span>
    <span class="sep">·</span>
    <span id="s-last">—</span>
    <span style="margin-left:auto">AionCode</span>
  </div>
</div>

<!-- Command Palette -->
<div class="palette-bg" id="pal-bg" onclick="closePalette(event)">
  <div class="palette" onclick="event.stopPropagation()">
    <input id="pal-in" type="text" placeholder="搜索命令..." autocomplete="off" oninput="filterCmd(this.value)" onkeydown="palKey(event)">
    <div class="palette-list" id="pal-list"></div>
  </div>
</div>

<script>
/* AionCode Copilot — Core: view switching, data loading, SSE, palette, theme */

let curProject = null, curEncoded = null, sse = null, curView = 'overview';

const api = async (p, o = {}) => {
  const r = await fetch(p, { headers: {'Content-Type':'application/json'}, ...o, body: o.body ? JSON.stringify(o.body) : undefined });
  return r.json();
};
const enc = p => btoa(p).replace(/\+/g,'-').replace(/\//g,'_').replace(/=/g,'');
const esc = s => s ? s.replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/>/g,'&gt;') : '';
const fmtSz = b => b<1024?b+'B':b<1048576?(b/1024).toFixed(1)+'K':(b/1048576).toFixed(1)+'M';
const fmtTs = d => d ? new Date(d).toLocaleTimeString([],{hour:'2-digit',minute:'2-digit',second:'2-digit'}) : '';

document.addEventListener('DOMContentLoaded', () => { loadProjects(); setupKeys(); });

// ══════════════════════════════════════
//  View Switching
// ══════════════════════════════════════
function switchView(view) {
  curView = view;
  document.querySelectorAll('.rail-btn[data-view]').forEach(b =>
    b.classList.toggle('active', b.dataset.view === view));
  document.querySelectorAll('.view-sidebar').forEach(el =>
    el.classList.toggle('hidden', el.id !== 'vs-' + view));
  if (typeof ensureViewData === 'function') ensureViewData(view);
  showViewDetail(view);
}

function showViewDetail(view) {
  const d = document.getElementById('detail');
  switch (view) {
    case 'overview':
      d.innerHTML = '<div class="detail-overview" id="detail-overview"></div>';
      loadOverviewDetail(); break;
    case 'files':
      d.innerHTML = `<div class="detail-welcome"><div class="welcome-icon">◇</div>
        <div class="welcome-title">选择文件查看内容</div>
        <div class="welcome-hint">点击左侧文件树中的文件</div></div>`; break;
    case 'monitor':
      d.innerHTML = '<div class="detail-monitor" id="detail-monitor"></div>';
      loadMonitorDetail(); break;
    case 'bugs':
      d.innerHTML = `<div class="detail-welcome"><div class="welcome-icon">●</div>
        <div class="welcome-title">选择缺陷查看详情</div>
        <div class="welcome-hint">点击左侧缺陷列表中的条目</div></div>`; break;
    case 'team':
      d.innerHTML = '<div class="detail-team" id="detail-team"></div>';
      loadTeamDetail(); break;
    case 'about':
      d.innerHTML = renderAboutPage(); break;
    case 'specs':
      d.innerHTML = `<div class="detail-welcome"><div class="welcome-icon">📋</div>
        <div class="welcome-title">选择需求文档查看详情</div>
        <div class="welcome-hint">点击左侧列表中的条目</div></div>`; break;
    case 'plans':
      d.innerHTML = `<div class="detail-welcome"><div class="welcome-icon">📊</div>
        <div class="welcome-title">选择方案查看详情</div>
        <div class="welcome-hint">点击左侧列表中的条目</div></div>`; break;
    case 'rules':
      d.innerHTML = `<div class="detail-welcome"><div class="welcome-icon">🛡</div>
        <div class="welcome-title">选择规则文件查看详情</div>
        <div class="welcome-hint">点击左侧列表中的条目</div></div>`; break;
    case 'checklists':
      d.innerHTML = `<div class="detail-welcome"><div class="welcome-icon">✓</div>
        <div class="welcome-title">选择清单查看详情</div>
        <div class="welcome-hint">点击左侧列表中的条目</div></div>`; break;
    case 'test':
      d.innerHTML = `<div class="detail-welcome"><div class="welcome-icon">⚡</div>
        <div class="welcome-title">选择测试文件查看内容</div>
        <div class="welcome-hint">点击左侧列表中的条目</div></div>`; break;
    case 'changelog':
      d.innerHTML = `<div class="detail-welcome"><div class="welcome-icon">⏱</div>
        <div class="welcome-title">选择日志条目查看详情</div>
        <div class="welcome-hint">点击左侧变更日志列表</div></div>`; break;
  }
}

// ══════════════════════════════════════
//  Projects
// ══════════════════════════════════════
async function loadProjects() {
  const list = await api('/api/projects');
  const sel = document.getElementById('proj-sel');
  sel.innerHTML = '';
  if (!list.length) { sel.innerHTML = '<option>无项目</option>'; return; }
  list.forEach(p => {
    const o = document.createElement('option');
    o.value = p.path; o.textContent = p.name + (p.has_aion ? '' : ' ⚠');
    sel.appendChild(o);
  });
  switchProject(list[0].path);
}

async function switchProject(path) {
  if (!path) return;
  curProject = path; curEncoded = enc(path);
  document.getElementById('proj-path').textContent = path;
  document.getElementById('s-proj').textContent = path.split('/').pop();
  if (typeof resetViewsCache === 'function') resetViewsCache();
  await Promise.all([loadStats(), loadFiles(), loadEvents(), loadBugs(), loadTeam()]);
  switchView(curView);
  startSSE();
}

// ══════════════════════════════════════
//  Overview (sidebar stats)
// ══════════════════════════════════════
async function loadStats() {
  const d = await api(`/api/projects/${curEncoded}/stats`);
  if (!d.ok) return;
  window._stats = d;
  const items = [
    { v: d.rules?.total??0, l: '规则' }, { v: d.specs??0, l: '需求' },
    { v: d.plans??0, l: '方案' }, { v: d.reviews??0, l: '审查' },
    { v: d.bugs??0, l: '缺陷' }, { v: d.commands??0, l: '命令' },
  ];
  document.getElementById('stats').innerHTML = items.map(s =>
    `<div class="stat"><div class="stat-val">${s.v}</div><div class="stat-lbl">${s.l}</div></div>`
  ).join('');
}

// ══════════════════════════════════════
//  Files
// ══════════════════════════════════════
async function loadFiles() {
  const d = await api(`/api/projects/${curEncoded}/files`);
  if (!d.ok) return;
  window._fileTree = d.tree || [];
  document.getElementById('ftree').innerHTML = buildTree(d.tree, 0);
}

function buildTree(items, depth) {
  if (!items?.length) return '<div class="empty">空目录</div>';
  return items.map(n => {
    const pad = `padding-left:${4+depth*14}px`;
    if (n.type === 'dir') {
      return `<div class="fnode dir" style="${pad}" onclick="this.nextElementSibling.classList.toggle('closed')">
        <span class="ico">▸</span>${esc(n.name)}/
      </div><div class="fnode-children${depth>0?' closed':''}">${buildTree(n.children,depth+1)}</div>`;
    }
    return `<div class="fnode" style="${pad}" onclick="viewFile(this,'${esc(n.path)}')" title="${esc(n.path)}">
      <span class="ico">·</span>${esc(n.name)}<span class="sz">${fmtSz(n.size)}</span>
    </div>`;
  }).join('');
}

async function viewFile(el, path) {
  document.querySelectorAll('.fnode.active').forEach(n => n.classList.remove('active'));
  el.classList.add('active');
  const d = await api(`/api/projects/${curEncoded}/file?path=${encodeURIComponent(path)}`);
  if (!d.ok) return;
  const fname = path.split('/').pop();
  document.getElementById('detail').innerHTML = `
    <div class="detail-file">
      <div class="detail-file-header">
        <span class="fname">${esc(fname)}</span>
        <span class="fpath">${esc(path)}</span>
        <span class="spacer"></span>
        <button class="close-btn" onclick="switchView('files')">✕</button>
      </div>
      <pre>${esc(d.content)}</pre>
    </div>`;
}

// ══════════════════════════════════════
//  Monitor (sidebar events)
// ══════════════════════════════════════
async function loadEvents() {
  const d = await api(`/api/projects/${curEncoded}/events/recent?limit=30`);
  if (!d.ok) return;
  window._events = d.events || [];
  renderEventsSidebar(window._events);
}

function renderEventsSidebar(evts) {
  document.getElementById('b-events').textContent = evts.length || '—';
  const el = document.getElementById('events');
  if (!evts.length) { el.innerHTML = '<div class="empty">暂无事件</div>'; return; }
  el.innerHTML = evts.slice(0, 20).map(e =>
    `<div class="evt"><span class="evt-ts">${fmtTs(e.ts)}</span><span class="evt-msg">${esc(e.summary)}</span></div>`
  ).join('');
  if (evts[0]?.ts) document.getElementById('s-last').textContent = fmtTs(evts[0].ts);
}

function startSSE() {
  if (sse) sse.close();
  sse = new EventSource(`/api/projects/${curEncoded}/events/stream`);
  const dot = document.getElementById('live-dot');
  sse.onmessage = e => {
    try {
      const evt = JSON.parse(e.data);
      const data = evt.data || evt;
      const tool = data.tool_name || data.tool || data.hook_event_name || 'event';
      const now = fmtTs(new Date());
      const el = document.getElementById('events');
      const empty = el.querySelector('.empty'); if (empty) empty.remove();
      const div = document.createElement('div');
      div.className = 'evt';
      div.innerHTML = `<span class="evt-ts">${now}</span><span class="evt-msg">${esc(tool)}</span>`;
      el.prepend(div);
      while (el.children.length > 20) el.lastChild.remove();
      document.getElementById('s-last').textContent = now;
      dot.style.display = 'inline-block';
    } catch(_){}
  };
  document.getElementById('s-dot').className = 'status-dot';
  sse.onerror = () => { document.getElementById('s-dot').className = 'status-dot err'; dot.style.display='none'; };
}

// ══════════════════════════════════════
//  Bugs (sidebar)
// ══════════════════════════════════════
async function loadBugs() {
  const d = await api(`/api/projects/${curEncoded}/bugs`);
  if (!d.ok) return;
  window._bugs = d.bugs || [];
  const badge = document.getElementById('b-bugs');
  badge.textContent = window._bugs.length || '—';
  badge.className = 'sw-badge' + (window._bugs.length > 0 ? ' warn' : '');
  const el = document.getElementById('bugs');
  if (!window._bugs.length) { el.innerHTML = '<div class="empty">无缺陷 ✓</div>'; return; }
  el.innerHTML = window._bugs.map((b, i) =>
    `<div class="bug" onclick="viewBug(${i})">
      <span class="bug-dot ${b.severity||'medium'}"></span>
      <span class="bug-id">${esc(b.id)}</span>
      <span class="bug-title">${esc(b.title)}</span>
      <span class="tag">${b.status||'open'}</span>
    </div>`
  ).join('');
}

// ══════════════════════════════════════
//  Team (sidebar)
// ══════════════════════════════════════
async function loadTeam() {
  const d = await api(`/api/projects/${curEncoded}/team`);
  if (!d.ok) return;
  window._team = d;
  const members = d.team || [];
  const el = document.getElementById('team');
  if (!members.length) { el.innerHTML = '<div class="empty">未配置团队</div>'; return; }
  el.innerHTML = members.map(m =>
    `<div class="member">
      <div class="avatar">${(m.name||'?')[0].toUpperCase()}</div>
      <div><div class="member-name">${esc(m.name)}</div><div class="member-role">${esc(m.role||'member')}</div></div>
    </div>`
  ).join('');
}

// ══════════════════════════════════════
//  Command Palette
// ══════════════════════════════════════
const CMDS = [
  { ico: '◈', lbl: '概览', fn: () => switchView('overview') },
  { ico: '◇', lbl: '文件', fn: () => switchView('files') },
  { ico: '◎', lbl: '监控', fn: () => switchView('monitor') },
  { ico: '●', lbl: '缺陷', fn: () => switchView('bugs') },
  { ico: '◉', lbl: '团队', fn: () => switchView('team') },
  { ico: '☰', lbl: '需求', fn: () => switchView('specs') },
  { ico: '▤', lbl: '方案', fn: () => switchView('plans') },
  { ico: '◆', lbl: '规则', fn: () => switchView('rules') },
  { ico: '☑', lbl: '清单', fn: () => switchView('checklists') },
  { ico: '⚡', lbl: '测试', fn: () => switchView('test') },
  { ico: '⏱', lbl: '日志', fn: () => switchView('changelog') },
  { ico: '↻', lbl: '刷新全部', fn: () => switchProject(curProject) },
  { ico: '+', lbl: '添加项目', fn: addProject },
  { ico: '◐', lbl: '切换主题', fn: toggleTheme },
  { ico: 'ⓘ', lbl: '关于', fn: () => switchView('about') },
];
let cmdIdx = 0, cmdF = [...CMDS];

function openPalette() {
  document.getElementById('pal-bg').classList.add('open');
  const inp = document.getElementById('pal-in');
  inp.value = ''; inp.focus(); cmdF = [...CMDS]; cmdIdx = 0; renderCmds();
}
function closePalette(e) {
  if (e && e.target !== document.getElementById('pal-bg')) return;
  document.getElementById('pal-bg').classList.remove('open');
}
function filterCmd(q) { const l = q.toLowerCase(); cmdF = CMDS.filter(c => c.lbl.includes(l)); cmdIdx = 0; renderCmds(); }
function renderCmds() {
  document.getElementById('pal-list').innerHTML = cmdF.map((c,i) =>
    `<div class="palette-opt${i===cmdIdx?' sel':''}" onclick="runCmd(${i})" onmouseenter="cmdIdx=${i};renderCmds()">
      <span class="ico">${c.ico}</span><span class="lbl">${c.lbl}</span>${c.key?`<span class="key">${c.key}</span>`:''}
    </div>`
  ).join('');
}
function palKey(e) {
  if (e.key==='Escape') { closePalette({}); return; }
  if (e.key==='ArrowDown') { cmdIdx=Math.min(cmdIdx+1,cmdF.length-1); renderCmds(); e.preventDefault(); }
  if (e.key==='ArrowUp') { cmdIdx=Math.max(cmdIdx-1,0); renderCmds(); e.preventDefault(); }
  if (e.key==='Enter'&&cmdF[cmdIdx]) runCmd(cmdIdx);
}
function runCmd(i) { closePalette({}); cmdF[i]?.fn(); }
function setupKeys() {
  document.addEventListener('keydown', e => {
    if ((e.metaKey||e.ctrlKey) && e.key==='k') { e.preventDefault(); openPalette(); }
    if (e.key==='Escape') closePalette({});
  });
}
async function addProject() {
  const p = prompt('输入项目路径:');
  if (!p) return;
  const d = await api('/api/projects/add', { method:'POST', body:{path:p} });
  d.ok ? loadProjects() : alert(d.message);
}

// ══════════════════════════════════════
//  Theme
// ══════════════════════════════════════
function toggleTheme() {
  const html = document.documentElement;
  const cur = html.getAttribute('data-theme') || 'dark';
  const next = cur === 'dark' ? 'light' : 'dark';
  html.setAttribute('data-theme', next);
  localStorage.setItem('aioncode-theme', next);
  document.getElementById('theme-btn').textContent = next === 'dark' ? '☀' : '☾';
}

(function() {
  const saved = localStorage.getItem('aioncode-theme');
  if (saved) {
    document.documentElement.setAttribute('data-theme', saved);
    const btn = document.getElementById('theme-btn');
    if (btn) btn.textContent = saved === 'dark' ? '☀' : '☾';
  }
})();

</script>
<script>
/* AionCode Copilot — View renderers + data views */
function parseFrontmatter(content) {
  const m = content.match(/^---\n([\s\S]*?)\n---\n?([\s\S]*)$/);
  if (!m) return { meta: {}, body: content };
  const meta = {};
  m[1].split('\n').forEach(line => {
    const kv = line.match(/^(\w[\w_-]*)\s*:\s*(.+)$/);
    if (kv) meta[kv[1]] = kv[2].replace(/^["']|["']$/g, '').trim();
  });
  return { meta, body: m[2] };
}
function applyInline(text) {
  return text
    .replace(/\*\*(.+?)\*\*/g, '<strong>$1</strong>')
    .replace(/\*(.+?)\*/g, '<em>$1</em>')
    .replace(/`([^`]+)`/g, '<code>$1</code>')
    .replace(/\[([^\]]+)\]\(([^)]+)\)/g, '<a href="$2" target="_blank">$1</a>');
}
function renderMarkdown(text) {
  let html = '';
  let inCode = false, inList = false, listType = '';
  const lines = text.split('\n');
  for (const raw of lines) {
    if (raw.trimStart().startsWith('```')) {
      if (inCode) { html += '</code></pre>'; inCode = false; }
      else { html += '<pre><code>'; inCode = true; }
      continue;
    }
    if (inCode) { html += esc(raw) + '\n'; continue; }
    let line = esc(raw);
    if (inList && !line.match(/^(\s*[-*]\s|^\s*\d+\.\s|^\s*- \[[ x]\])/)) {
      html += listType === 'ul' ? '</ul>' : '</ol>'; inList = false;
    }
    if (line.match(/^### /)) { html += '<h3>' + line.slice(4) + '</h3>'; continue; }
    if (line.match(/^## /)) { html += '<h2>' + line.slice(3) + '</h2>'; continue; }
    if (line.match(/^# /)) { html += '<h1>' + line.slice(2) + '</h1>'; continue; }
    if (line.match(/^-{3,}$/)) { html += '<hr>'; continue; }
    if (line.match(/^- \[x\] /)) {
      if (!inList) { html += '<ul style="list-style:none;padding-left:4px">'; inList = true; listType = 'ul'; }
      html += '<li><div class="check-row"><span class="check-box checked">✓</span>' + applyInline(line.slice(6)) + '</div></li>';
      continue;
    }
    if (line.match(/^- \[ \] /)) {
      if (!inList) { html += '<ul style="list-style:none;padding-left:4px">'; inList = true; listType = 'ul'; }
      html += '<li><div class="check-row"><span class="check-box"></span>' + applyInline(line.slice(6)) + '</div></li>';
      continue;
    }
    if (line.match(/^\s*[-*]\s/)) {
      if (!inList) { html += '<ul>'; inList = true; listType = 'ul'; }
      html += '<li>' + applyInline(line.replace(/^\s*[-*]\s/, '')) + '</li>';
      continue;
    }
    if (line.match(/^\s*\d+\.\s/)) {
      if (!inList) { html += '<ol>'; inList = true; listType = 'ol'; }
      html += '<li>' + applyInline(line.replace(/^\s*\d+\.\s/, '')) + '</li>';
      continue;
    }
    if (line.match(/^\|/)) {
      if (line.match(/^\|[\s-:|]+\|$/)) continue;
      const cells = line.split('|').filter(c => c.trim());
      if (!html.includes('<table>') || html.endsWith('</table>')) {
        html += '<table><tr>' + cells.map(c => '<th>' + applyInline(c.trim()) + '</th>').join('') + '</tr>';
      } else {
        html += '<tr>' + cells.map(c => '<td>' + applyInline(c.trim()) + '</td>').join('') + '</tr>';
      }
      continue;
    }
    if (html.includes('<table>') && !html.endsWith('</table>') && !line.match(/^\|/)) {
      html += '</table>';
    }
    if (!line.trim()) { html += '<br>'; continue; }
    html += '<p>' + applyInline(line) + '</p>';
  }
  if (inCode) html += '</code></pre>';
  if (inList) html += listType === 'ul' ? '</ul>' : '</ol>';
  if (html.includes('<table>') && !html.endsWith('</table>')) html += '</table>';
  return html;
}
function renderFrontmatterTable(meta) {
  if (!meta || !Object.keys(meta).length) return '';
  const statusBadge = v => {
    const cls = ['completed','active','in_progress','deprecated','pending'].find(s => v.includes(s));
    return cls ? `<span class="fm-badge ${cls}">${esc(v)}</span>` : esc(v);
  };
  const rows = Object.entries(meta).map(([k, v]) => {
    const val = k === 'status' ? statusBadge(v) : esc(v);
    return `<tr><td>${esc(k)}</td><td>${val}</td></tr>`;
  }).join('');
  return `<table class="fm-table">${rows}</table>`;
}
async function loadDirFiles(subdir) {
  if (!window._fileTree) {
    const d = await api(`/api/projects/${curEncoded}/files`);
    if (!d.ok) return [];
    window._fileTree = d.tree || [];
  }
  const dir = window._fileTree.find(n => n.name === subdir && n.type === 'dir');
  return dir ? (dir.children || []).filter(f => f.type === 'file') : [];
}
async function loadFileContent(path) {
  const d = await api(`/api/projects/${curEncoded}/file?path=${encodeURIComponent(path)}`);
  if (!d.ok) return null;
  return { ...parseFrontmatter(d.content), raw: d.content, path: d.path };
}
const viewsLoaded = new Set();
function ensureViewData(view) {
  if (viewsLoaded.has(view)) return;
  viewsLoaded.add(view);
  switch(view) {
    case 'specs': loadSpecs(); break;
    case 'plans': loadPlans(); break;
    case 'rules': loadRules(); break;
    case 'checklists': loadChecklists(); break;
    case 'test': loadTests(); break;
    case 'changelog': loadChangelog(); break;
  }
}
function resetViewsCache() {
  viewsLoaded.clear();
  window._fileTree = null;
  window._clEntries = null;
}
async function loadSpecs() {
  const files = await loadDirFiles('specs');
  const el = document.getElementById('specs-list');
  document.getElementById('b-specs').textContent = files.length || '—';
  if (!files.length) { el.innerHTML = '<div class="empty">暂无需求文档</div>'; return; }
  const items = [];
  for (const f of files) {
    const data = await loadFileContent(f.path);
    const title = data?.meta?.title || data?.body?.match(/^#\s+(.+)/m)?.[1] || f.name.replace('.md','');
    const status = data?.meta?.status || '';
    const date = data?.meta?.created_at || '';
    items.push({ path: f.path, title, status, date });
  }
  el.innerHTML = items.map(it =>
    `<div class="data-item" onclick="viewDataItem('${esc(it.path)}')" title="${esc(it.path)}">
      <div class="data-item-title">${esc(it.title)}</div>
      <div class="data-item-meta">
        ${it.status ? `<span class="fm-badge ${it.status}">${esc(it.status)}</span>` : ''}
        ${it.date ? `<span>${esc(it.date)}</span>` : ''}
      </div>
    </div>`
  ).join('');
}
async function loadPlans() {
  const files = await loadDirFiles('plans');
  const el = document.getElementById('plans-list');
  document.getElementById('b-plans').textContent = files.length || '—';
  if (!files.length) { el.innerHTML = '<div class="empty">暂无实施方案</div>'; return; }
  const items = [];
  for (const f of files) {
    const data = await loadFileContent(f.path);
    const title = data?.meta?.title || data?.body?.match(/^#\s+(.+)/m)?.[1] || f.name.replace('.md','');
    const status = data?.meta?.status || '';
    const cur = parseInt(data?.meta?.current_step) || 0;
    const total = parseInt(data?.meta?.total_steps) || 0;
    const pct = total > 0 ? Math.round(cur / total * 100) : 0;
    items.push({ path: f.path, title, status, cur, total, pct });
  }
  el.innerHTML = items.map(it =>
    `<div class="data-item" onclick="viewDataItem('${esc(it.path)}')">
      <div class="data-item-title">${esc(it.title)}</div>
      <div class="data-item-meta">
        ${it.status ? `<span class="fm-badge ${it.status}">${esc(it.status)}</span>` : ''}
        ${it.total ? `<span>${it.cur}/${it.total}</span><div class="check-progress"><div class="check-progress-fill" style="width:${it.pct}%"></div></div>` : ''}
      </div>
    </div>`
  ).join('');
}
async function loadRules() {
  const files = await loadDirFiles('rules');
  const el = document.getElementById('rules-list');
  if (!files.length) { el.innerHTML = '<div class="empty">暂无规则</div>'; document.getElementById('b-rules').textContent = '—'; return; }
  let totalRules = 0;
  let html = '';
  for (const f of files) {
    const data = await loadFileContent(f.path);
    const category = data?.meta?.category || f.name.replace('.md','');
    const count = parseInt(data?.meta?.rule_count) || 0;
    totalRules += count;
    html += `<div class="rule-group-header">${esc(category)} (${count})</div>`;
    html += `<div class="data-item" onclick="viewDataItem('rules/${esc(f.name)}')">
      <div class="data-item-title">${esc(f.name)}</div>
      <div class="data-item-meta"><span>${count} 条规则</span></div>
    </div>`;
  }
  document.getElementById('b-rules').textContent = totalRules || '—';
  el.innerHTML = html;
}
async function loadChecklists() {
  const files = await loadDirFiles('checklists');
  const el = document.getElementById('checklists-list');
  document.getElementById('b-checklists').textContent = files.length || '—';
  if (!files.length) { el.innerHTML = '<div class="empty">暂无清单</div>'; return; }
  const items = [];
  for (const f of files) {
    const data = await loadFileContent(f.path);
    const body = data?.body || data?.raw || '';
    const total = (body.match(/- \[[ x]\]/g) || []).length;
    const done = (body.match(/- \[x\]/g) || []).length;
    const pct = total > 0 ? Math.round(done / total * 100) : 0;
    items.push({ path: f.path, name: f.name.replace('.md',''), done, total, pct });
  }
  el.innerHTML = items.map(it =>
    `<div class="data-item" onclick="viewDataItem('${esc(it.path)}')">
      <div class="data-item-title">${esc(it.name)}</div>
      <div class="data-item-meta">
        <span>${it.done}/${it.total}</span>
        <div class="check-progress"><div class="check-progress-fill" style="width:${it.pct}%"></div></div>
      </div>
    </div>`
  ).join('');
}
async function loadTests() {
  const files = await loadDirFiles('tests');
  const el = document.getElementById('test-list');
  if (!window._fileTree) {
    const d = await api(`/api/projects/${curEncoded}/files`);
    if (d.ok) window._fileTree = d.tree || [];
  }
  const testsDir = (window._fileTree || []).find(n => n.name === 'tests' && n.type === 'dir');
  if (!testsDir || !testsDir.children?.length) {
    el.innerHTML = '<div class="empty">暂无测试报告</div>';
    document.getElementById('b-test').textContent = '—';
    return;
  }
  let totalFiles = 0;
  let html = '';
  for (const child of testsDir.children) {
    if (child.type === 'dir') {
      const subFiles = child.children || [];
      totalFiles += subFiles.length;
      html += `<div class="rule-group-header">${esc(child.name)}/ (${subFiles.length})</div>`;
      subFiles.forEach(f => {
        html += `<div class="data-item" onclick="viewDataItem('tests/${esc(child.name)}/${esc(f.name)}')">
          <div class="data-item-title">${esc(f.name)}</div>
          <div class="data-item-meta"><span>${fmtSz(f.size)}</span></div>
        </div>`;
      });
      if (!subFiles.length) html += '<div class="empty">空目录</div>';
    } else {
      totalFiles++;
      html += `<div class="data-item" onclick="viewDataItem('tests/${esc(child.name)}')">
        <div class="data-item-title">${esc(child.name)}</div>
        <div class="data-item-meta"><span>${fmtSz(child.size)}</span></div>
      </div>`;
    }
  }
  document.getElementById('b-test').textContent = totalFiles || '—';
  el.innerHTML = html;
}
async function loadChangelog() {
  const d = await api(`/api/projects/${curEncoded}/changelog?limit=50`);
  window._clEntries = d.entries || [];
  const el = document.getElementById('changelog-list');
  document.getElementById('b-changelog').textContent = window._clEntries.length || '—';
  if (!window._clEntries.length) { el.innerHTML = '<div class="empty">暂无变更记录</div>'; return; }
  el.innerHTML = window._clEntries.map((e, i) => {
    const parts = e.header.split('|');
    const date = parts[0]?.trim() || '';
    const title = parts[1]?.trim() || e.header;
    return `<div class="cl-entry" onclick="viewChangelogEntry(${i})">
      <div class="cl-entry-date">${esc(date)}</div>
      <div class="cl-entry-title">${esc(title)}</div>
    </div>`;
  }).join('');
}
function viewChangelogEntry(idx) {
  const e = window._clEntries?.[idx];
  if (!e) return;
  document.querySelectorAll('.cl-entry').forEach((el, i) => el.classList.toggle('active', i === idx));
  const parts = e.header.split('|');
  const date = parts[0]?.trim() || '';
  const title = parts[1]?.trim() || e.header;
  document.getElementById('detail').innerHTML = `<div class="md-content">
    <h1>${esc(title)}</h1>
    <p style="color:var(--text-tertiary);font-size:11px;margin-bottom:16px">${esc(date)}</p>
    ${renderMarkdown(e.body)}
  </div>`;
}
async function viewDataItem(path) {
  document.querySelectorAll('.data-item').forEach(el => el.classList.remove('active'));
  event?.target?.closest('.data-item')?.classList.add('active');
  const data = await loadFileContent(path);
  if (!data) { document.getElementById('detail').innerHTML = '<div class="detail-welcome"><div class="welcome-title">文件加载失败</div></div>'; return; }
  const fname = path.split('/').pop();
  document.getElementById('detail').innerHTML = `<div class="md-content">
    <div style="display:flex;align-items:center;gap:8px;margin-bottom:12px">
      <h1 style="margin:0;flex:1">${esc(fname)}</h1>
      <button class="close-btn" onclick="switchView(curView)" style="border:none;background:transparent;color:var(--text-tertiary);cursor:pointer;padding:2px 6px;border-radius:3px;font-size:14px">✕</button>
    </div>
    ${renderFrontmatterTable(data.meta)}
    ${renderMarkdown(data.body)}
  </div>`;
}
const ABOUT_SECTIONS = [
  { id:'what',      title:'什么是 AionCode' },
  { id:'install',   title:'安装与初始化' },
  { id:'workflow',  title:'工作流指南' },
  { id:'commands',  title:'命令速查' },
  { id:'scenarios', title:'常见场景' },
  { id:'dashboard', title:'副驾驶面板' },
  { id:'shortcuts', title:'快捷操作' },
  { id:'faq',       title:'常见问题' },
  { id:'roadmap',   title:'版本路线图' },
];
function renderAboutToc() {
  document.getElementById('about-toc').innerHTML = ABOUT_SECTIONS.map(s =>
    `<div class="fnode" style="padding-left:4px;cursor:pointer" onclick="scrollAbout('${s.id}')">
      <span class="ico">§</span>${s.title}
    </div>`
  ).join('');
}
function scrollAbout(id) {
  const el = document.getElementById('about-' + id);
  if (el) el.scrollIntoView({ behavior: 'smooth', block: 'start' });
}
function _tbl(hdrs, rows) {
  return `<table class="key-table"><tr>${hdrs.map(h=>'<th>'+h+'</th>').join('')}</tr>${rows.map(r=>'<tr>'+r.map(c=>'<td>'+c+'</td>').join('')+'</tr>').join('')}</table>`;
}
function _flow(steps) {
  return `<div class="flow">${steps.map(s=>`<span class="flow-step">${s}</span>`).join('<span class="flow-arrow">→</span>')}</div>`;
}
function _faq(q, a) { return `<p><strong>Q：${q}</strong></p><p>${a}</p>`; }
function renderAboutPage() {
  setTimeout(renderAboutToc, 0);
  const cmds = [
    ['准备','<code>aion-scan</code>','扫描已有项目，建立初始智能数据'],
    ['','<code>aion-think</code>','质疑假设，在开始前暴露盲点'],
    ['','<code>aion-help</code>','查看所有命令和工作流说明'],
    ['设计','<code>aion-design</code>','将想法转化为结构化需求规格'],
    ['','<code>aion-demo</code>','生成交互式 HTML 原型（可选）'],
    ['','<code>aion-plan</code>','创建分步实施计划'],
    ['实施','<code>aion-impl</code>','按计划编写代码（自动遵守规则）'],
    ['','<code>aion-test</code>','生成测试、分析覆盖率'],
    ['质量','<code>aion-verify</code>','运行构建、测试、lint、类型检查'],
    ['','<code>aion-review</code>','代码审查 + 自动提取规则'],
    ['管理','<code>aion-commit</code>','安全提交（需 review 通过）'],
    ['','<code>aion-save</code>','保存对话上下文到 .aion/ 和 memory'],
    ['','<code>aion-bug</code>','Bug 管理：报告/列表/分配/关闭'],
    ['','<code>aion-crosscheck</code>','用其他 AI 模型交叉验证代码'],
  ];
  return `<div class="about">
    <h1>AionCode 使用指南</h1>
    <p class="subtitle">AI 原生开发智能框架 · 让 AI 编程有章可循</p>
    <h2 id="about-what">什么是 AionCode</h2>
    <p>AionCode 是一个 <strong>AI 辅助开发的智能框架</strong>。它为你的项目建立一套结构化的知识体系（规则、规格、计划），让 AI（Claude Code）在编码时有据可循。</p>
    <p style="margin-top:8px">核心理念：<strong>知识沉淀 → 规则驱动 → 质量可控</strong></p>
    ${_tbl(['组成','作用'],[['<code>.aion/</code> 目录','项目智能数据：规则、规格、计划、日志、Bug'],['<code>commands/</code>','18 个 AI 工作流命令'],['<code>aioncode</code> CLI','命令行工具：初始化、升级、副驾驶'],['副驾驶面板','Web 可视化界面（你正在看的这个）']])}
    <h2 id="about-install">安装与初始化</h2>
    <p><strong>第一步：</strong>在项目根目录执行 <code>aioncode init</code>。初始化后你会得到：</p>
    ${_tbl(['目录/文件','用途'],[['<code>.aion/rules/</code>','项目编码规则（风格、陷阱、性能）'],['<code>.aion/specs/</code>','需求规格文档'],['<code>.aion/plans/</code>','实施计划'],['<code>.aion/changelog.md</code>','工作变更历史'],['<code>.aion/bugs/</code>','Bug 报告'],['<code>.claude/CLAUDE.md</code>','项目索引（每次启动自动加载）'],['<code>.claude/commands/</code>','AI 工作流命令']])}
    <p><strong>第二步：</strong>（可选）在 Claude Code 中运行 <code>/project:aion-scan</code>，AI 自动分析项目并提取初始规则。</p>
    <h2 id="about-workflow">工作流指南</h2>
    <p><strong>新项目：</strong></p>${_flow(['think','design','plan','impl','verify','review','commit'])}
    <p style="margin-top:12px"><strong>已有项目：</strong></p>${_flow(['scan','impl/design','verify','review','commit'])}
    <p style="margin-top:12px"><strong>Bug 修复：</strong></p>${_flow(['bug report','impl {BUG-ID}','verify','review','commit'])}
    <p style="margin-top:8px">所有命令在 Claude Code 终端中以 <code>/project:aion-xxx</code> 格式调用。</p>
    <h2 id="about-commands">命令速查</h2>
    <table class="key-table"><tr><th>阶段</th><th>命令</th><th>说明</th></tr>${cmds.map(r=>'<tr>'+r.map(c=>'<td>'+c+'</td>').join('')+'</tr>').join('')}</table>
    <h2 id="about-scenarios">常见场景</h2>
    <p><strong>场景 1：给项目加新功能</strong></p>
    <ol><li>运行 <code>/project:aion-design</code> 描述需求</li><li>运行 <code>/project:aion-plan</code> 生成实施计划</li><li>运行 <code>/project:aion-impl</code> AI 按计划写代码</li><li><code>verify</code> → <code>review</code> → <code>commit</code></li></ol>
    <p style="margin-top:12px"><strong>场景 2：让 AI 修 Bug</strong></p>
    <ol><li><code>/project:aion-bug report</code> 描述 Bug → AI 创建报告（如 B-0322-1）</li><li><code>/project:aion-impl B-0322-1</code> → verify → review → commit</li></ol>
    <p style="margin-top:12px"><strong>场景 3：交叉验证</strong> — 运行 <code>/project:aion-crosscheck --model gemini</code>，发现的问题自动生成 Bug 报告。</p>
    <p style="margin-top:12px"><strong>场景 4：接手别人的项目</strong> — <code>aioncode init</code> → <code>/project:aion-scan</code> → AI 自动建立项目智能数据。</p>
    <h2 id="about-dashboard">副驾驶面板</h2>
    <p>副驾驶是 <strong>CLI 的可视化外壳</strong>。CLI 是手，副驾驶是眼。</p>
    ${_tbl(['视图','用途','使用时机'],[['◈ 概览','项目统计 + 变更历史','开始工作前了解状态'],['◇ 文件','浏览 .aion/ 配置文件','查看 rules、specs、plans'],['◎ 监控','SSE 实时事件流','Claude Code 会话进行中'],['● 缺陷','Bug 列表与详情','crosscheck/review 后'],['◉ 团队','成员、模型、风险配置','团队协作配置时']])}
    <p style="margin-top:8px"><strong>启动：</strong><code>aioncode dashboard</code>（生产）/ <code>--dev</code>（开发）/ <code>--port 8080</code>（自定义端口）</p>
    ${_tbl(['CLI 操作','副驾驶显示'],[['<code>/aion-impl</code> 写代码','监控视图：实时工具调用'],['<code>/aion-review</code> 审查','文件视图：review 结果'],['<code>/aion-bug report</code>','缺陷视图：新 Bug'],['<code>/aion-crosscheck</code>','缺陷视图：交叉验证问题']])}
    <h2 id="about-shortcuts">快捷操作</h2>
    ${_tbl(['快捷键','操作'],[['<kbd>⌘</kbd><kbd>K</kbd> / <kbd>Ctrl</kbd><kbd>K</kbd>','打开命令面板'],['<kbd>Esc</kbd>','关闭命令面板'],['顶部下拉框','切换项目'],['☀ / ☾ 按钮','切换深色/浅色主题']])}
    <h2 id="about-faq">常见问题</h2>
    ${_faq('AionCode 支持哪些 AI 模型？','目前命令仅在 Claude Code 环境中执行。crosscheck 可调用其他模型（如 Gemini）做交叉验证。')}
    ${_faq('.aion/ 目录要提交到 Git 吗？','建议提交。<code>rules/</code>、<code>specs/</code>、<code>plans/</code> 是团队共享知识。<code>sessions.jsonl</code> 和 <code>monitor/</code> 已被 .gitignore 排除。')}
    ${_faq('如何升级？','运行 <code>aioncode upgrade</code> 或 <code>/project:aion-upgrade</code>。升级只更新命令和工具，不覆盖项目数据。')}
    ${_faq('review 不通过能提交吗？','不能。<code>aion-commit</code> 要求通过 review（docs-only 可豁免）。')}
    ${_faq('如何自定义规则？','直接编辑 <code>.aion/rules/</code> 下的文件，或运行 <code>/project:aion-scan</code> 自动提取。')}
    <h2 id="about-roadmap">版本路线图</h2>
    <ul>
      <li><strong>v0.5</strong>（当前）— FastAPI 重构 + 副驾驶 UI + Core 层统一</li>
      <li><strong>v0.6</strong> — 云端 MVP：意图日志管道 + 多项目统计</li>
      <li><strong>v0.7</strong> — 云端完整：团队管理 + Bug 看板 + 规则共享</li>
    </ul>
  </div>`;
}
async function loadOverviewDetail() {
  const el = document.getElementById('detail-overview');
  if (!el || !curEncoded) return;
  const s = window._stats || {};
  const cl = await api(`/api/projects/${curEncoded}/changelog?limit=5`);
  const entries = cl.entries || [];
  const se = await api(`/api/projects/${curEncoded}/sessions?limit=5`);
  const sessions = se.sessions || [];
  el.innerHTML = `
    <div class="do-section">
      <h3 class="do-title">项目统计</h3>
      <div class="do-grid">
        <div class="do-card">
          <div class="do-card-val">${s.rules?.style??0}</div><div class="do-card-lbl">代码风格</div>
        </div>
        <div class="do-card">
          <div class="do-card-val">${s.rules?.pitfalls??0}</div><div class="do-card-lbl">已知陷阱</div>
        </div>
        <div class="do-card">
          <div class="do-card-val">${s.rules?.perf??0}</div><div class="do-card-lbl">性能规则</div>
        </div>
        <div class="do-card">
          <div class="do-card-val">${s.commands??0}</div><div class="do-card-lbl">命令数</div>
        </div>
        <div class="do-card">
          <div class="do-card-val">${s.specs??0}</div><div class="do-card-lbl">需求文档</div>
        </div>
        <div class="do-card">
          <div class="do-card-val">${s.plans??0}</div><div class="do-card-lbl">实施方案</div>
        </div>
      </div>
    </div>
    <div class="do-section">
      <h3 class="do-title">变更历史</h3>
      ${entries.length ? entries.map(e => `
        <div class="do-entry">
          <div class="do-entry-head">${esc(e.header)}</div>
          <div class="do-entry-body">${esc(e.body).substring(0, 200)}</div>
        </div>`).join('') : '<div class="empty">暂无记录</div>'}
    </div>
    <div class="do-section">
      <h3 class="do-title">最近会话</h3>
      ${sessions.length ? sessions.map(s => `
        <div class="do-session">
          <span class="do-session-ts">${esc(s.started_at || s.ts || '')}</span>
          <span class="do-session-info">工具 ${Object.keys(s.tools_used||{}).length} 种 · 文件 ${(s.files_changed||[]).length} 个</span>
        </div>`).join('') : '<div class="empty">暂无会话</div>'}
    </div>`;
}
async function loadMonitorDetail() {
  const el = document.getElementById('detail-monitor');
  if (!el || !curEncoded) return;
  const state = await api(`/api/monitor/${curEncoded}/state`);
  if (!state.ok) return;
  const tools = state.tools || {};
  const files = state.files_changed || [];
  const toolEntries = Object.entries(tools).sort((a,b) => b[1]-a[1]);
  const maxCount = toolEntries.length ? toolEntries[0][1] : 1;
  el.innerHTML = `
    <div class="do-section">
      <h3 class="do-title">会话状态</h3>
      <div class="do-grid">
        <div class="do-card"><div class="do-card-val">${state.total_events}</div><div class="do-card-lbl">总事件</div></div>
        <div class="do-card"><div class="do-card-val">${toolEntries.length}</div><div class="do-card-lbl">工具种类</div></div>
        <div class="do-card"><div class="do-card-val">${files.length}</div><div class="do-card-lbl">文件变更</div></div>
        <div class="do-card"><div class="do-card-val">${(state.agents||[]).length}</div><div class="do-card-lbl">子代理</div></div>
      </div>
    </div>
    <div class="do-section">
      <h3 class="do-title">工具使用分布</h3>
      ${toolEntries.length ? toolEntries.map(([name, count]) => `
        <div class="do-bar-row">
          <span class="do-bar-label">${esc(name)}</span>
          <div class="do-bar-track"><div class="do-bar-fill" style="width:${(count/maxCount*100).toFixed(0)}%"></div></div>
          <span class="do-bar-val">${count}</span>
        </div>`).join('') : '<div class="empty">暂无数据</div>'}
    </div>
    <div class="do-section">
      <h3 class="do-title">变更文件</h3>
      ${files.length ? files.map(f => `<div class="do-file-item">→ ${esc(f.split('/').slice(-2).join('/'))}</div>`).join('') : '<div class="empty">暂无文件变更</div>'}
    </div>`;
}
function viewBug(idx) {
  const b = window._bugs[idx];
  if (!b) return;
  document.getElementById('detail').innerHTML = `
    <div class="detail-bug">
      <h2>${esc(b.title)}</h2>
      <div class="meta">
        <span class="tag">${esc(b.id)}</span>
        <span class="tag">${esc(b.severity||'medium')}</span>
        <span class="tag">${esc(b.status||'open')}</span>
        ${b.assignee ? `<span class="tag">→ ${esc(b.assignee)}</span>` : ''}
      </div>
      <div class="body">${esc(b.body||'无描述')}</div>
    </div>`;
}
async function loadTeamDetail() {
  const el = document.getElementById('detail-team');
  if (!el) return;
  const t = window._team || {};
  const members = t.team || [];
  const models = t.models || {};
  const risk = t.risk_keywords || {};
  el.innerHTML = `
    <div class="do-section">
      <h3 class="do-title">成员 (${members.length})</h3>
      ${members.length ? members.map(m => `
        <div class="do-member-card">
          <div class="avatar" style="width:32px;height:32px;font-size:14px;border-radius:6px">${(m.name||'?')[0].toUpperCase()}</div>
          <div>
            <div style="font-weight:600;font-size:13px">${esc(m.name)}</div>
            <div style="font-size:11px;color:var(--text-tertiary)">${esc(m.role||'member')}${m.git_email ? ' · '+esc(m.git_email) : ''}</div>
            ${m.expertise ? `<div style="font-size:10px;color:var(--text-tertiary);margin-top:2px">专长: ${esc(Array.isArray(m.expertise)?m.expertise.join(', '):m.expertise)}</div>` : ''}
          </div>
        </div>`).join('') : '<div class="empty">未配置成员</div>'}
    </div>
    <div class="do-section">
      <h3 class="do-title">模型配置</h3>
      ${Object.keys(models).length ? Object.entries(models).map(([k,v]) => `
        <div class="do-kv"><span class="do-kv-k">${esc(k)}</span><span class="do-kv-v">${esc(v)}</span></div>
      `).join('') : '<div class="empty">未配置</div>'}
    </div>
    <div class="do-section">
      <h3 class="do-title">风险关键词</h3>
      ${Object.keys(risk).length ? Object.entries(risk).map(([k,v]) => `
        <div class="do-kv"><span class="do-kv-k">${esc(k)}</span><span class="do-kv-v">${esc(v)}</span></div>
      `).join('') : '<div class="empty">未配置</div>'}
    </div>`;
}

</script>
</body>
</html>
"""

EMBEDDED_MONITOR_HTML = """<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>AionCode — Mission Control</title>
<style>
:root {
  --space-bg: #0a0e14;
  --surface: #131820;
  --border: #1e2833;
  --text: #c5d0de;
  --blue: #58a6ff;
  --amber: #d29922;
  --red: #f85149;
  --green: #3fb950;
  --cyan: #56d4dd;
  --purple: #bc8cff;
  --font: 'SF Mono', 'Fira Code', monospace;
}

* { margin: 0; padding: 0; box-sizing: border-box; }

body {
  font-family: var(--font);
  background: var(--space-bg);
  color: var(--text);
  height: 100vh;
  display: flex;
  flex-direction: column;
  overflow: hidden;
}

/* Header */
.mc-header {
  display: flex;
  align-items: center;
  padding: 12px 20px;
  border-bottom: 1px solid var(--border);
  gap: 20px;
}

.mc-title { color: var(--cyan); font-weight: 700; font-size: 14px; letter-spacing: 2px; }
.mc-met { color: var(--amber); font-size: 20px; font-weight: 700; }

.mc-status {
  margin-left: auto;
  display: flex;
  gap: 16px;
  font-size: 11px;
}

.mc-metric {
  display: flex;
  flex-direction: column;
  align-items: center;
  padding: 4px 12px;
  background: var(--surface);
  border: 1px solid var(--border);
  border-radius: 4px;
  min-width: 80px;
}

.mc-metric-value { font-size: 18px; font-weight: 700; color: var(--blue); }
.mc-metric-label { font-size: 9px; color: var(--text); text-transform: uppercase; letter-spacing: 1px; }

/* Main */
.mc-main {
  flex: 1;
  display: grid;
  grid-template-columns: 1fr 1fr;
  gap: 1px;
  background: var(--border);
  overflow: hidden;
}

.mc-panel {
  background: var(--space-bg);
  display: flex;
  flex-direction: column;
  overflow: hidden;
}

.mc-panel-title {
  padding: 8px 14px;
  font-size: 10px;
  letter-spacing: 2px;
  text-transform: uppercase;
  color: var(--cyan);
  border-bottom: 1px solid var(--border);
}

.mc-panel-body {
  flex: 1;
  overflow-y: auto;
  padding: 8px 14px;
  font-size: 11px;
  line-height: 1.6;
}

/* Log entries */
.log-entry { display: flex; gap: 8px; padding: 2px 0; }
.log-ts { color: var(--amber); min-width: 80px; }
.log-tool { color: var(--blue); min-width: 60px; }
.log-msg { color: var(--text); word-break: break-all; }

/* Agents */
.agent-item {
  display: flex;
  align-items: center;
  gap: 8px;
  padding: 6px 0;
  border-bottom: 1px solid var(--border);
}

.agent-dot { width: 6px; height: 6px; border-radius: 50%; background: var(--green); }
.agent-type { color: var(--purple); }

/* Files */
.file-change { padding: 3px 0; color: var(--text); }
.file-change::before { content: '→ '; color: var(--green); }

/* Scrollbar */
::-webkit-scrollbar { width: 4px; }
::-webkit-scrollbar-track { background: transparent; }
::-webkit-scrollbar-thumb { background: var(--border); border-radius: 2px; }
</style>
</head>
<body>

<div class="mc-header">
  <span class="mc-title">MISSION CONTROL</span>
  <span class="mc-met" id="met">T+00:00:00</span>
  <div class="mc-status">
    <div class="mc-metric">
      <span class="mc-metric-value" id="m-events">0</span>
      <span class="mc-metric-label">Events</span>
    </div>
    <div class="mc-metric">
      <span class="mc-metric-value" id="m-tools">0</span>
      <span class="mc-metric-label">Tools</span>
    </div>
    <div class="mc-metric">
      <span class="mc-metric-value" id="m-files">0</span>
      <span class="mc-metric-label">Files</span>
    </div>
    <div class="mc-metric">
      <span class="mc-metric-value" id="m-agents">0</span>
      <span class="mc-metric-label">Agents</span>
    </div>
  </div>
</div>

<div class="mc-main">
  <div class="mc-panel">
    <div class="mc-panel-title">Event Log</div>
    <div class="mc-panel-body" id="log-panel"></div>
  </div>
  <div class="mc-panel">
    <div class="mc-panel-title">Active Agents</div>
    <div class="mc-panel-body" id="agent-panel">
      <div style="color:var(--text);opacity:0.4;padding:20px;text-align:center">Waiting for agents...</div>
    </div>
  </div>
  <div class="mc-panel" style="grid-column: 1 / -1;">
    <div class="mc-panel-title">Files Changed</div>
    <div class="mc-panel-body" id="files-panel" style="display:flex;flex-wrap:wrap;gap:4px;align-content:flex-start;">
      <div style="color:var(--text);opacity:0.4;padding:20px">No file changes detected</div>
    </div>
  </div>
</div>

<script>
// Extract project encoded from URL: /monitor/{encoded}
const pathParts = window.location.pathname.split('/');
const encoded = pathParts[pathParts.length - 1];
let sessionStart = null;
let eventCount = 0;
const toolSet = new Set();
const fileSet = new Set();
const agents = [];

// MET clock
function updateMET() {
  if (!sessionStart) { document.getElementById('met').textContent = 'T+00:00:00'; return; }
  const elapsed = Math.floor((Date.now() - sessionStart) / 1000);
  const h = String(Math.floor(elapsed / 3600)).padStart(2, '0');
  const m = String(Math.floor((elapsed % 3600) / 60)).padStart(2, '0');
  const s = String(elapsed % 60).padStart(2, '0');
  document.getElementById('met').textContent = `T+${h}:${m}:${s}`;
}
setInterval(updateMET, 1000);

// Load initial state
fetch(`/api/monitor/${encoded}/state`).then(r => r.json()).then(state => {
  if (!state.ok) return;
  if (state.session?.start) sessionStart = new Date(state.session.start).getTime();
  eventCount = state.total_events || 0;
  document.getElementById('m-events').textContent = eventCount;

  if (state.tools) {
    Object.keys(state.tools).forEach(t => toolSet.add(t));
    document.getElementById('m-tools').textContent = toolSet.size;
  }
  if (state.files_changed) {
    state.files_changed.forEach(f => fileSet.add(f));
    document.getElementById('m-files').textContent = fileSet.size;
    renderFiles();
  }
  if (state.agents) {
    state.agents.forEach(a => agents.push(a));
    document.getElementById('m-agents').textContent = agents.length;
    renderAgents();
  }
});

// SSE
const sse = new EventSource(`/api/projects/${encoded}/events/stream`);
sse.onmessage = (e) => {
  try {
    const evt = JSON.parse(e.data);
    const data = evt.data || evt;
    if (!sessionStart) sessionStart = Date.now();

    eventCount++;
    document.getElementById('m-events').textContent = eventCount;

    const tool = data.tool_name || data.tool || '';
    if (tool) { toolSet.add(tool); document.getElementById('m-tools').textContent = toolSet.size; }

    const fp = data.tool_input?.file_path;
    if (fp && (tool === 'Edit' || tool === 'Write')) {
      fileSet.add(fp);
      document.getElementById('m-files').textContent = fileSet.size;
      renderFiles();
    }

    const hook = data.hook_event_name || '';
    if (hook.startsWith('Subagent')) {
      agents.push({ type: data.subagent_type || 'unknown', ts: new Date().toISOString() });
      document.getElementById('m-agents').textContent = agents.length;
      renderAgents();
    }

    // Add log entry
    addLog(evt.ts || new Date().toISOString(), tool || hook, fp || data.tool_input?.command?.substring(0, 80) || '');
  } catch (_) {}
};

function addLog(ts, tool, msg) {
  const panel = document.getElementById('log-panel');
  const div = document.createElement('div');
  div.className = 'log-entry';
  const time = new Date(ts).toLocaleTimeString();
  div.innerHTML = `<span class="log-ts">${time}</span><span class="log-tool">${esc(tool)}</span><span class="log-msg">${esc(msg)}</span>`;
  panel.prepend(div);
  while (panel.children.length > 200) panel.lastChild.remove();
}

function renderAgents() {
  const panel = document.getElementById('agent-panel');
  panel.innerHTML = agents.slice(-20).reverse().map(a =>
    `<div class="agent-item"><span class="agent-dot"></span><span class="agent-type">${esc(a.type)}</span></div>`
  ).join('');
}

function renderFiles() {
  const panel = document.getElementById('files-panel');
  const sorted = [...fileSet].sort();
  panel.innerHTML = sorted.map(f => {
    const name = f.split('/').pop();
    return `<div class="file-change" title="${esc(f)}">${esc(name)}</div>`;
  }).join('');
}

function esc(s) {
  if (!s) return '';
  return s.replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/>/g,'&gt;');
}
</script>
</body>
</html>
"""
